#!/usr/bin/env bash
# =============================================================================
#  pi-kiosk-setup.sh — set up a Raspberry Pi as a Chromium kiosk for the wallboard
# -----------------------------------------------------------------------------
#  Target: Raspberry Pi OS (Bookworm). Auto-detects Wayland (labwc/wayfire) vs
#  X11 and installs an autostart that:
#     - launches Chromium full-screen kiosk -> http://dashboard.home
#     - disables screen blanking / DPMS
#     - hides the mouse cursor
#     - auto-restarts Chromium if it crashes
#
#  Run as the desktop user (NOT root):   bash pi-kiosk-setup.sh
#  Re-runnable (idempotent). Reboot when done.   See pi-kiosk.md for details.
# =============================================================================
set -euo pipefail

URL="${WALLBOARD_URL:-http://dashboard.home}"
USER_NAME="$(id -un)"

if [[ "$USER_NAME" == "root" ]]; then
  echo "Run this as your normal desktop user, not root."; exit 1
fi

echo "==> Installing packages (chromium, unclutter)…"
sudo apt-get update -y
# Package name differs across images; try both.
sudo apt-get install -y chromium-browser 2>/dev/null || sudo apt-get install -y chromium
sudo apt-get install -y unclutter wlr-randr 2>/dev/null || true

# Locate the chromium binary.
CHROME="$(command -v chromium-browser || command -v chromium || true)"
[[ -z "$CHROME" ]] && { echo "Chromium not found after install."; exit 1; }
echo "==> Chromium: $CHROME"

# Chromium flags shared by both sessions.
read -r -d '' CHROME_FLAGS <<EOF || true
--kiosk --noerrordialogs --disable-infobars --incognito \
--check-for-update-interval=31536000 --disable-session-crashed-bubble \
--disable-features=Translate --autoplay-policy=no-user-gesture-required \
--password-store=basic --no-first-run --start-fullscreen
EOF

# --- The relaunch wrapper: restart Chromium if it ever exits ---------------
KIOSK="$HOME/.local/bin/wallboard-kiosk.sh"
mkdir -p "$HOME/.local/bin"
cat > "$KIOSK" <<EOF
#!/usr/bin/env bash
# Auto-generated by pi-kiosk-setup.sh — relaunches Chromium kiosk on crash.
URL="$URL"
CHROME="$CHROME"
FLAGS="$CHROME_FLAGS"

# X11 only: disable blanking + hide cursor (no-ops under Wayland).
if [ "\${XDG_SESSION_TYPE:-}" = "x11" ] || [ -n "\${DISPLAY:-}" ]; then
  xset s off || true; xset -dpms || true; xset s noblank || true
  (unclutter -idle 0 &) 2>/dev/null || true
fi

# Use a clean profile dir so a previous crash flag never blocks startup.
PROFILE="\$HOME/.config/wallboard-chromium"
rm -rf "\$PROFILE/Singleton"* 2>/dev/null || true

while true; do
  "\$CHROME" \$FLAGS --user-data-dir="\$PROFILE" "\$URL"
  echo "Chromium exited (\$?). Restarting in 3s…" >&2
  sleep 3
done
EOF
chmod +x "$KIOSK"
echo "==> Wrote relaunch wrapper: $KIOSK"

# --- Detect session type and install the right autostart -------------------
SESSION="${XDG_SESSION_TYPE:-}"
if [[ -z "$SESSION" ]]; then
  # Best-effort guess from what's installed.
  if command -v labwc >/dev/null || command -v wayfire >/dev/null; then SESSION="wayland"; else SESSION="x11"; fi
fi
echo "==> Session type: $SESSION"

if command -v wayfire >/dev/null; then
  echo "==> Configuring wayfire autostart (~/.config/wayfire.ini)"
  WF="$HOME/.config/wayfire.ini"
  touch "$WF"
  if ! grep -q '^\[autostart\]' "$WF"; then printf '\n[autostart]\n' >> "$WF"; fi
  grep -q 'wallboard-kiosk' "$WF" || cat >> "$WF" <<EOF
kiosk = $KIOSK
# Keep the panel awake
idle = false
EOF

elif command -v labwc >/dev/null; then
  echo "==> Configuring labwc autostart (~/.config/labwc/autostart)"
  mkdir -p "$HOME/.config/labwc"
  AS="$HOME/.config/labwc/autostart"
  touch "$AS"
  grep -q 'wallboard-kiosk' "$AS" || cat >> "$AS" <<EOF
# Disable display power management so the panel never sleeps
wlr-randr --output "\$(wlr-randr | head -1 | cut -d' ' -f1)" --on >/dev/null 2>&1 &
$KIOSK &
EOF

else
  echo "==> Configuring X11 autostart (LXDE / systemd user service)"
  # Try LXDE-pi autostart first
  AUTO="$HOME/.config/lxsession/LXDE-pi/autostart"
  mkdir -p "$(dirname "$AUTO")"
  touch "$AUTO"
  if ! grep -q 'wallboard-kiosk' "$AUTO"; then
    {
      echo "@xset s off"
      echo "@xset -dpms"
      echo "@xset s noblank"
      echo "@unclutter -idle 0"
      echo "@$KIOSK"
    } >> "$AUTO"
  fi
fi

echo
echo "==> Done. Reboot to start the kiosk:   sudo reboot"
echo "    URL: $URL"
echo "    (Ensure the Pi uses Pi-hole 192.168.1.190 for DNS so dashboard.home resolves.)"
